# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Fengguo"
email = ""
link = ""
avatar = "https://ucgimgview.fmapp.com/attachv1/image/20231114/20231114193452_98806.png"
